service: mega-experts-ci-cd-group-examination-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: ${env:AWS_REGION}
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:5173'
        - ${env:GITHUB_PAGES_URL}
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - X-Amzn-Trace-Id
      allowCredentials: true
  environment:
    TABLE_NAME: ${env:TABLE_NAME}
    SECRET_KEY: ${env:SECRET_KEY}

useDotenv: true
plugins:
  - serverless-webpack
package:
  individually: true
custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'

functions:
  login:
    handler: src/functions/User/login.handler
    events:
      - httpApi: 'POST /api/auth/login'
  register:
    handler: src/functions/User/register.handler
    events:
      - httpApi: 'POST /api/auth/register'
  getMeetups:
    handler: src/functions/Meetup/getMeetups.handler
    events:
      - httpApi: 'GET /api/meetups'
  getMeetup:
    handler: src/functions/Meetup/getMeetup.handler
    events:
      - httpApi: 'GET /api/meetups/{id}'
  meetupReg:
    handler: src/functions/Meetup/meetupRegistration.handler
    events:
      - httpApi: 'POST /api/meetups/{id}'
  addReview:
    handler: src/functions/Meetup/addReview.handler
    events:
      - httpApi: 'POST /api/meetups/review/{id}'

resources:
  Resources:
    Database:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL