name: Deploy To Github Pages on Push to Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm install
        working-directory: ./frontend # Set the working directory to your frontend folder

      - name: Build dist
        run: npm run build
        working-directory: ./frontend # Set the working directory to your frontend folder

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './frontend/dist' # Set the path to your frontend/dist folder

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
